import { User } from "@/store/auth/auth.types"

export const patientTableData: User[] = [
  {
    uuid: "usr_001",
    first_name: "Brayan",
    last_name: "Mlawa",
    email: "brayanmlawa@gmail.com",
    phone: "+255 754 100 201",
    username: "brayan.mlawa",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_002",
    first_name: "Amina",
    last_name: "Kassim",
    email: "amina.kassim@gmail.com",
    phone: "+255 719 220 411",
    username: "amina.kassim",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_003",
    first_name: "Daniel",
    last_name: "Kimaro",
    email: "daniel.kimaro@gmail.com",
    phone: "+255 716 443 100",
    username: "daniel.kimaro",
    role: "Patient",
    is_active: false,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_004",
    first_name: "Neema",
    last_name: "Hassan",
    email: "neema.hassan@gmail.com",
    phone: "+255 746 873 901",
    username: "neema.hassan",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_005",
    first_name: "Victor",
    last_name: "Mrema",
    email: "victor.mrema@gmail.com",
    phone: "+255 753 901 122",
    username: "victor.mrema",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_006",
    first_name: "Janeth",
    last_name: "Paul",
    email: "janeth.paul@gmail.com",
    phone: "+255 784 550 098",
    username: "janeth.paul",
    role: "Patient",
    is_active: false,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_007",
    first_name: "Ruth",
    last_name: "Kileo",
    email: "ruth.kileo@gmail.com",
    phone: "+255 748 662 210",
    username: "ruth.kileo",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_008",
    first_name: "Michael",
    last_name: "Otieno",
    email: "michael.otieno@gmail.com",
    phone: "+255 765 120 882",
    username: "michael.otieno",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_009",
    first_name: "Grace",
    last_name: "Anthony",
    email: "grace.anthony@gmail.com",
    phone: "+255 757 800 404",
    username: "grace.anthony",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_010",
    first_name: "Emmanuel",
    last_name: "Jacob",
    email: "emmanuel.jacob@gmail.com",
    phone: "+255 782 190 734",
    username: "emmanuel.jacob",
    role: "Patient",
    is_active: false,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_011",
    first_name: "Asha",
    last_name: "Moshi",
    email: "asha.moshi@gmail.com",
    phone: "+255 762 340 555",
    username: "asha.moshi",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_012",
    first_name: "Kelvin",
    last_name: "Nyangasa",
    email: "kelvin.nyangasa@gmail.com",
    phone: "+255 771 611 808",
    username: "kelvin.nyangasa",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_013",
    first_name: "Fatma",
    last_name: "Said",
    email: "fatma.said@gmail.com",
    phone: "+255 756 201 303",
    username: "fatma.said",
    role: "Patient",
    is_active: false,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_014",
    first_name: "Joseph",
    last_name: "Mushi",
    email: "joseph.mushi@gmail.com",
    phone: "+255 753 410 121",
    username: "joseph.mushi",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
  {
    uuid: "usr_015",
    first_name: "Halima",
    last_name: "Yahya",
    email: "halima.yahya@gmail.com",
    phone: "+255 784 911 601",
    username: "halima.yahya",
    role: "Patient",
    is_active: true,
    is_admin: false,
    is_staff: false,
  },
]
